openapi: 3.0.3
info:
  title: Repo Tokenizer MCP API
  version: 0.1.0
servers:
  - url: http://localhost:4000
paths:
  /health:
    get:
      summary: Health check
      responses:
        '200':
          description: OK
  /index:
    post:
      summary: Trigger repository indexing
      requestBody:
        content:
          application/json:
            schema:
              type: object
              properties:
                ref:
                  type: string
      responses:
        '202':
          description: Indexing scheduled
  /files:
    get:
      summary: List indexed files
      parameters:
        - in: query
          name: include
          schema:
            type: string
        - in: query
          name: exclude
          schema:
            type: string
        - in: query
          name: ref
          schema:
            type: string
      responses:
        '200':
          description: List of files
  /file:
    get:
      summary: Get file content
      parameters:
        - in: query
          name: path
          required: true
          schema:
            type: string
        - in: query
          name: ref
          schema:
            type: string
      responses:
        '200':
          description: File payload
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/FileResponse'
  /chunks:
    get:
      summary: List indexed chunks
      parameters:
        - in: query
          name: path
          schema:
            type: string
        - in: query
          name: lang
          schema:
            type: string
        - in: query
          name: maxTokens
          schema:
            type: integer
        - in: query
          name: stream
          schema:
            type: string
        - in: query
          name: ref
          schema:
            type: string
      responses:
        '200':
          description: List of chunks
  /chunks/{id}:
    get:
      summary: Fetch chunk by id
      parameters:
        - in: path
          name: id
          required: true
          schema:
            type: string
        - in: query
          name: ref
          schema:
            type: string
      responses:
        '200':
          description: Chunk payload
  /search:
    get:
      summary: Full-text search within chunks
      parameters:
        - in: query
          name: q
          required: true
          schema:
            type: string
        - in: query
          name: pathGlob
          schema:
            type: string
        - in: query
          name: ref
          schema:
            type: string
      responses:
        '200':
          description: Search results
  /search/symbols:
    get:
      summary: Symbol search
      parameters:
        - in: query
          name: q
          schema:
            type: string
        - in: query
          name: ref
          schema:
            type: string
      responses:
        '200':
          description: Symbol matches
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/SymbolSearchResponse'
  /export/jsonl:
    get:
      summary: Export current index as JSONL
      responses:
        '200':
          description: JSONL stream
          content:
            application/x-ndjson:
              schema:
                type: string
                format: binary
  /export/sqlite:
    get:
      summary: Export current index as SQLite database
      responses:
        '200':
          description: SQLite binary
          content:
            application/vnd.sqlite3:
              schema:
                type: string
                format: binary
components:
  schemas:
    SecretFinding:
      type: object
      properties:
        path:
          type: string
        line:
          type: integer
        ruleId:
          type: string
        excerpt:
          type: string
    FileResponse:
      type: object
      properties:
        file:
          type: object
          properties:
            path:
              type: string
            size:
              type: integer
            hash:
              type: string
            language:
              type: string
            executable:
              type: boolean
            content:
              type: string
            secrets:
              type: array
              items:
                $ref: '#/components/schemas/SecretFinding'
    SymbolSearchResponse:
      type: object
      properties:
        matches:
          type: array
          items:
            type: object
            properties:
              symbol:
                type: string
              path:
                type: string
              line:
                type: integer
              context:
                type: string
